### ISSUE TITLE
Data source "host" crashing Terraform provider

### ISSUE THREAD

**Issue by sahaqaa** [OpenVPN/terraform-provider-cloudconnexa#18]
```
resource "cloudconnexa_host" "test-host" {
  name = "test-host"
  connector {
    name          = "connector01"
    vpn_region_id = "eu-central-1"
  }
}

data "cloudconnexa_host" "name" {
  name = "connector01"
}
output "name" {
  value = data.cloudconnexa_host.name
}
```

Output:
```
olytvyn@oleksandr-lytvyn:~/GIT/testing_code/temp_stuff$ terraform apply 
data.cloudconnexa_host.name: Reading...
data.cloudconnexa_network.test-net: Reading...
cloudconnexa_host.test-host: Refreshing state... [id=7a2eb0e2-92f7-4007-8efc-9fbb4f3d9c93]
╷
│ Error: Request cancelled
│ 
│   with data.cloudconnexa_network.test-net,
│   on main.tf line 1, in data "cloudconnexa_network" "test-net":
│    1: data "cloudconnexa_network" "test-net" {
│ 
│ The plugin.(*GRPCProvider).ReadDataSource request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with cloudconnexa_host.test-host,
│   on main.tf line 63, in resource "cloudconnexa_host" "test-host":
│   63: resource "cloudconnexa_host" "test-host" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with data.cloudconnexa_host.name,
│   on main.tf line 71, in data "cloudconnexa_host" "name":
│   71: data "cloudconnexa_host" "name" {
│ 
│ The plugin.(*GRPCProvider).ReadDataSource request was cancelled.
╵

Stack trace from the terraform-provider-cloudconnexa plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d7122]

goroutine 146 [running]:
github.com/OpenVPN/terraform-provider-cloudconnexa/cloudconnexa.dataSourceHostRead({0xd9e150?, 0xc000906db0?}, 0x0?, {0xb7d180?, 0xc000434000})
        /home/olytvyn/go/src/github.com/OpenVPN/terraform-provider-cloudconnexa/cloudconnexa/data_source_host.go:96 +0x122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003a8a80, {0xd9e150, 0xc000906db0}, 0xd?, {0xb7d180, 0xc000434000})
        /home/olytvyn/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0003a8a80, {0xd9e150, 0xc000906db0}, 0xc000792580, {0xb7d180, 0xc000434000})
        /home/olytvyn/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1015 +0x149
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003942a0, {0xd9e150?, 0xc000906cc0?}, 0xc000672100)
        /home/olytvyn/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1291 +0x366
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0002a0be0, {0xd9e150?, 0xc000906300?}, 0xc0004b8280)
        /home/olytvyn/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:686 +0x416
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xc56ac0?, 0xc0002a0be0}, {0xd9e150, 0xc000906300}, 0xc000792000, 0x0)
        /home/olytvyn/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c7000, {0xd9e150, 0xc000906270}, {0xda23b8, 0xc0002a6180}, 0xc0005a0000, 0xc00039ccf0, 0x12bc6a0, 0x0)
        /home/olytvyn/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001c7000, {0xda23b8, 0xc0002a6180}, 0xc0005a0000)
        /home/olytvyn/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/olytvyn/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 12
        /home/olytvyn/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-cloudconnexa plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

olytvyn@oleksandr-lytvyn:~/GIT/testing_code/temp_stuff$ 
```

I.e. i can create new host, all OK. But when i try to use data source - Terraform provider crashes.

**Comment by sahaqaa** [comment]
It was fixed :heavy_check_mark:
